# ============================================================
# global.R
# ------------------------------------------------------------
# Loaded once when the Shiny app starts. Everything here is
# visible to ui.R, server.R, and all module files.
#
# Keep this file lean: packages, data, constants, helpers.
# ============================================================

# automatically see changes on save (for files)
options(shiny.autoreload = TRUE)

# ---- Packages ----
suppressPackageStartupMessages({
  library(shiny)
  library(bslib)
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(ggplot2)
  library(plotly)
  library(leaflet)
  library(sf)
  library(DT)
  library(zoo)
  library(scales)
  library(here)
  library(htmlwidgets)
  library(shinyWidgets)
})

# ---- Load prepared data ----
crime_path <- here("data", "lga_crime_long.rds")
sf_path    <- here("data", "nsw_lga_sf.rds")
court_path <- here("data", "court_data_clean.rds")
crime_db_path <- here("data", "crime_data_clean.rds")

if (!file.exists(crime_path)) {
  stop("Missing data/lga_crime_long.rds. ",
       "Run data-raw/01_prepare_lga_crime.R first.")
}
if (!file.exists(court_path)) {
  stop("Missing data/court_data_clean.rds. ",
        "Run data-raw/03_prepare_court.R first.")
}

if (!file.exists(crime_db_path)) {
  stop("Missing data/crime_data_clean.rds. ",
       "Run data-raw/04_prepare_crime.R first.")
}

crime_long <- readRDS(crime_path)
court_bundle <- readRDS(court_path)
crime_bundle <- readRDS(crime_db_path)

# Some rows in the prepared crime data have a rate but no stored rank.
# Recompute those ranks from the rate within each offence/year so LGAs
# like Sydney still participate in the ranked views.
crime_long <- crime_long |>
  group_by(offence, year) |>
  mutate(
    rank = if_else(
      is.na(rank) & !is.na(rate_per_100k),
      as.numeric(min_rank(desc(rate_per_100k))),
      rank
    )
  ) |>
  ungroup()

# sf may not be ready yet during early development — load lazily
nsw_lga_sf <- if (file.exists(sf_path)) readRDS(sf_path) else NULL

# ---- Constants ----
OFFENCE_CHOICES <- sort(unique(crime_long$offence))
YEAR_CHOICES    <- sort(unique(crime_long$year))
LGA_CHOICES     <- sort(unique(crime_long$lga))

COURT_TYPE <- sort(unique(court_bundle$main$Court.Type))

LATEST_YEAR <- max(crime_long$year, na.rm = TRUE)

# Greater Sydney LGAs — used for the "in and around Sydney" zoom view.
# Source: ABS Greater Capital City Statistical Area (GCCSA) definition.
SYDNEY_LGAS <- c(
  "Bayside", "Blacktown", "Blue Mountains", "Burwood", "Camden",
  "Campbelltown", "Canada Bay", "Canterbury-Bankstown", "Central Coast",
  "Cumberland", "Fairfield", "Georges River", "Hawkesbury", "Hornsby",
  "Hunters Hill", "Inner West", "Ku-ring-gai", "Lane Cove", "Liverpool",
  "Mosman", "North Sydney", "Northern Beaches", "Parramatta", "Penrith",
  "Randwick", "Ryde", "Strathfield", "Sutherland Shire", "Sydney",
  "The Hills Shire", "Waverley", "Willoughby", "Wollondilly", "Woollahra"
)

# ---- Theme ----
# Colour palette — kept consistent across all tabs so Varsha and Kavya
# can pull from these same names. Based on the learnui.design picker
# Kavya mentioned in the group chat.
APP_PALETTE <- list(
  primary    = "#1f4e79",   # deep navy — headers, primary accents
  secondary  = "#4a90c2",   # mid blue
  tertiary   = "#1abc9c",   # teal
  support1   = "#8e44ad",   # purple
  support2   = "#f4d03f",   # yellow
  support3   = "#7d8f2a",   # olive
  accent     = "#e67e22",   # warm orange for highlights / "strain"
  danger     = "#c0392b",   # red for high-rank / high-pressure
  neutral    = "#7f8c8d",   # muted grey
  bg         = "#f8f9fa",
  surface    = "#ffffff",
  text       = "#2c3e50"
)

# Discrete 30-shade palette for the choropleth.
# Generated by interpolating the ColorBrewer RdYlGn anchors into 30 equal
# steps. Rank 1 (worst) → shade 1 (dark red). Highest rank (safest) →
# shade 30 (dark green). The 30 discrete buckets mean adjacent ranks in
# the same bin share a colour, which reads better than a continuous ramp
# when you have ~128 LGAs but only care about the rough tier an LGA
# sits in.
CHOROPLETH_RAMP <- grDevices::colorRampPalette(
  c("#a50026",  # dark red    — most severe
    "#d73027",
    "#f46d43",
    "#fdae61",
    "#fee08b",  # yellow midpoint
    "#d9ef8b",
    "#a6d96a",
    "#66bd63",
    "#1a9850",
    "#006837")  # dark green  — safest
)(30)

N_SHADES <- length(CHOROPLETH_RAMP)  # 30

app_theme <- bs_theme(
  version   = 5,
  bootswatch = "flatly",
  primary   = APP_PALETTE$primary,
  secondary = APP_PALETTE$secondary,
  base_font = font_google("Inter"),
  heading_font = font_google("Inter", wght = "600"),
  "navbar-bg" = APP_PALETTE$primary
)

# ---- Helpers ----

#' Filter the long crime dataframe
#' @param offence character; one offence category
#' @param year integer; single year (or NULL for all)
#' @param lgas character vector of LGAs to keep (or NULL for all)
filter_crime <- function(offence = NULL, year = NULL, lgas = NULL) {
  df <- crime_long
  if (!is.null(offence)) df <- df |> filter(offence == !!offence)
  if (!is.null(year))    df <- df |> filter(year == !!year)
  if (!is.null(lgas))    df <- df |> filter(lga %in% lgas)
  df
}

#' Format a rate for display
fmt_rate <- function(x) {
  ifelse(is.na(x), "—", format(round(x, 0), big.mark = ","))
}

#' Format a rank with ordinal suffix
fmt_rank <- function(x) {
  ifelse(is.na(x), "—", paste0("#", x))
}
